package com.wansensoft.entities.organization;

import lombok.Data;

import java.util.Date;

@Data
public class OrgaUserRel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.orga_id
     *
     * @mbggenerated
     */
    private Long orgaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.user_blng_orga_dspl_seq
     *
     * @mbggenerated
     */
    private String userBlngOrgaDsplSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.delete_flag
     *
     * @mbggenerated
     */
    private String deleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.creator
     *
     * @mbggenerated
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.updater
     *
     * @mbggenerated
     */
    private Long updater;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jsh_orga_user_rel.tenant_id
     *
     * @mbggenerated
     */
    private Long tenantId;
}