/*
 * Copyright (C) 2023-2033 WanSen AI Team
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { GridMethods, TableMethods, TableEditMethods, TableValidatorMethods } from 'vxe-table';

export const gridComponentMethodKeys: (
  | keyof GridMethods
  | keyof TableMethods
  | keyof TableEditMethods
  | keyof TableValidatorMethods
)[] = [
  // vxe-grid 部分
  'dispatchEvent',
  'commitProxy',
  'getFormItems',
  'getPendingRecords',
  'zoom',
  'isMaximized',
  'maximize',
  'revert',
  'getProxyInfo',

  // vxe-table和vxe-grid公共部分
  'clearAll',
  'syncData',
  'updateData',
  'loadData',
  'reloadData',
  'reloadRow',
  'loadColumn',
  'reloadColumn',
  'getRowNode',
  'getColumnNode',
  'getRowIndex',
  'getVTRowIndex',
  'getVMRowIndex',
  'getColumnIndex',
  'getVTColumnIndex',
  'getVMColumnIndex',
  'createData',
  'createRow',
  'revertData',
  'clearData',
  'isInsertByRow',
  'isUpdateByRow',
  'getColumns',
  'getColumnById',
  'getColumnByField',
  'getTableColumn',
  'getData',
  'getCheckboxRecords',
  'getParentRow',
  'getRowSeq',
  'getRowById',
  'getRowid',
  'getTableData',
  'hideColumn',
  'showColumn',
  'resetColumn',
  'refreshColumn',
  'refreshScroll',
  'recalculate',
  'closeTooltip',
  'isAllCheckboxChecked',
  'isAllCheckboxIndeterminate',
  'getCheckboxIndeterminateRecords',
  'setCheckboxRow',
  'isCheckedByCheckboxRow',
  'isIndeterminateByCheckboxRow',
  'toggleCheckboxRow',
  'setAllCheckboxRow',
  'getRadioReserveRecord',
  'clearRadioReserve',
  'getCheckboxReserveRecords',
  'clearCheckboxReserve',
  'toggleAllCheckboxRow',
  'clearCheckboxRow',
  'setCurrentRow',
  'isCheckedByRadioRow',
  'setRadioRow',
  'clearCurrentRow',
  'clearRadioRow',
  'getCurrentRecord',
  'getRadioRecord',
  'getCurrentColumn',
  'setCurrentColumn',
  'clearCurrentColumn',
  'sort',
  'clearSort',
  'isSort',
  'getSortColumns',
  'closeFilter',
  'isFilter',
  'isRowExpandLoaded',
  'clearRowExpandLoaded',
  'reloadRowExpand',
  'reloadRowExpand',
  'toggleRowExpand',
  'setAllRowExpand',
  'setRowExpand',
  'isExpandByRow',
  'clearRowExpand',
  'clearRowExpandReserve',
  'getRowExpandRecords',
  'getTreeExpandRecords',
  'isTreeExpandLoaded',
  'clearTreeExpandLoaded',
  'reloadTreeExpand',
  'reloadTreeChilds',
  'toggleTreeExpand',
  'setAllTreeExpand',
  'setTreeExpand',
  'isTreeExpandByRow',
  'clearTreeExpand',
  'clearTreeExpandReserve',
  'getScroll',
  'scrollTo',
  'scrollToRow',
  'scrollToColumn',
  'clearScroll',
  'updateFooter',
  'updateStatus',
  'setMergeCells',
  'removeInsertRow',
  'removeMergeCells',
  'getMergeCells',
  'clearMergeCells',
  'setMergeFooterItems',
  'removeMergeFooterItems',
  'getMergeFooterItems',
  'clearMergeFooterItems',
  'openTooltip',
  'focus',
  'blur',
  'connect',

  // vxe-table-edit部分
  'insert',
  'insertAt',
  'remove',
  'removeCheckboxRow',
  'removeRadioRow',
  'removeCurrentRow',
  'getRecordset',
  'getInsertRecords',
  'getRemoveRecords',
  'getUpdateRecords',
  'getEditRecord',
  'getSelectedCell',
  'clearSelected',
  'isEditByRow',
  'setEditRow',
  'setEditCell',
  'setSelectCell',

  // vxe-table-validator
  'clearValidate',
  'fullValidate',
  'validate',

  //... 如有缺少在此处追加
  // xxx
];
